version: '3.8'

services:
  reverse-proxy:
    image: jwilder/nginx-proxy:latest
    restart: unless-stopped
    container_name: reverse-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs-volume:/etc/nginx/certs:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "acme:/etc/acme.sh"
    ports:
      - "80:80"
      - "443:443"
  nginx-letsencrypt-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "certs-volume:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "acme:/etc/acme.sh"
    environment:
      - NGINX_PROXY_CONTAINER=reverse-proxy
volumes:
  certs-volume:
  vhost:
  html:
  acme:
